-- Generated by Omni-God Instance2Lua
-- Target: ScreenGui
local Instances = {}

local obj1 = Instance.new("ScreenGui")
obj1.Name = "ScreenGui"
obj1.Parent = game:GetService('Players').LocalPlayer:WaitForChild('PlayerGui')

local obj2 = Instance.new("Frame")
obj2.Name = "BtnTgleGui"
obj2.Size = UDim2.new(0.0440270044, 0, 0.0868055522, 0)
obj2.Position = UDim2.new(0.0505376346, 0, 0.803819418, 0)
obj2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj2.BackgroundTransparency = 1
obj2.Transparency = 1
obj2.Visible = true
obj2.ZIndex = 1
obj2.BorderSizePixel = 0
obj2.Parent = obj1

local obj3 = Instance.new("Frame")
obj3.Name = "BackGO"
obj3.Size = UDim2.new(1.16354823, 0, 1.79354894, 0)
obj3.Position = UDim2.new(-0.0935479701, 0, -0.0874328613, 0)
obj3.BackgroundColor3 = Color3.fromRGB(72, 72, 72)
obj3.BackgroundTransparency = 0.4000000059604645
obj3.Transparency = 0.4000000059604645
obj3.Visible = true
obj3.ZIndex = 999
obj3.BorderSizePixel = 0
obj3.Parent = obj2

local gui = obj3 -- Đảm bảo obj3 đã được định nghĩa ở trên
local runService = game:GetService("RunService")

local angle = 0
local rotationSpeed = 30 -- Tốc độ xoay (độ trên giây)

-- RenderStepped giúp xoay cực kỳ mượt mà dựa trên khung hình (FPS)
runService.RenderStepped:Connect(function(deltaTime)
	-- Công thức: Góc mới = Góc cũ + (Tốc độ * thời gian chờ giữa 2 khung hình)
	angle = angle + rotationSpeed * deltaTime

	-- Kiểm tra nếu gui tồn tại để tránh lỗi "Attempt to index nil"
	if gui then
		gui.Rotation = angle
	end
end)

local obj5 = Instance.new("UICorner")
obj5.Name = "UICorner"
obj5.Parent = obj3

local obj6 = Instance.new("UIAspectRatioConstraint")
obj6.Name = "UIAspectRatioConstraint"
obj6.Parent = obj3

local obj7 = Instance.new("ImageButton")
obj7.Name = "ImageButton"
obj7.Size = UDim2.new(1.00763404, 0, 1.00691593, 0)
obj7.Position = UDim2.new(-0.00763397198, 0, -0.00785278343, 0)
obj7.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj7.BackgroundTransparency = 0
obj7.Image = "rbxassetid://88774721887954"
obj7.Transparency = 0
obj7.Visible = true
obj7.ZIndex = 1000
obj7.ImageColor3 = Color3.fromRGB(255, 255, 255)
obj7.BorderSizePixel = 0
obj7.Parent = obj2

local obj8 = Instance.new("UICorner")
obj8.Name = "UICorner"
obj8.Parent = obj7

local obj9 = Instance.new("UIAspectRatioConstraint")
obj9.Name = "UIAspectRatioConstraint"
obj9.Parent = obj7

local obj10 = Instance.new("UIAspectRatioConstraint")
obj10.Name = "UIAspectRatioConstraint"
obj10.Parent = obj2

local obj11 = Instance.new("Frame")
obj11.Name = "MainMenu"
obj11.Size = UDim2.new(0, 351, 0, 288)
obj11.Position = UDim2.new(0.0462283567, 0, 0.535590291, 0)
obj11.BackgroundColor3 = Color3.fromRGB(255, 140, 0)
obj11.BackgroundTransparency = 0.5
obj11.Transparency = 0.5
obj11.Visible = true
obj11.ZIndex = 1
obj11.BorderSizePixel = 0
obj11.Parent = obj1

local obj12 = Instance.new("UICorner")
obj12.Name = "UICorner"
obj12.Parent = obj11

local obj13 = Instance.new("TextLabel")
obj13.Name = "Name"
obj13.Size = UDim2.new(0, 351, 0, 50)
obj13.Position = UDim2.new(-0.00284900283, 0, -0.00227659475, 0)
obj13.Text = "SM Executor"
obj13.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj13.BackgroundTransparency = 1
obj13.Visible = true
obj13.ZIndex = 1
obj13.TextScaled = true
obj13.BorderSizePixel = 0
obj13.Font = Enum.Font.IndieFlower
obj13.Parent = obj11

local obj14 = Instance.new("UICorner")
obj14.Name = "UICorner"
obj14.Parent = obj13

local obj15 = Instance.new("TextLabel")
obj15.Name = "TextLabel"
obj15.Size = UDim2.new(0, 351, 0, 50)
obj15.Position = UDim2.new(0, 0, 0.0649746656, 0)
obj15.Text = "-------------------"
obj15.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj15.BackgroundTransparency = 1
obj15.Visible = true
obj15.ZIndex = 1
obj15.Font = Enum.Font.SourceSansBold
obj15.TextScaled = true
obj15.BorderSizePixel = 0
obj15.Parent = obj11

local obj16 = Instance.new("Frame")
obj16.Name = "Btn"
obj16.Size = UDim2.new(0, 290, 0, 207)
obj16.Position = UDim2.new(0.0883190855, 0, 0.203809947, 0)
obj16.BackgroundColor3 = Color3.fromRGB(255, 163, 15)
obj16.BackgroundTransparency = 0.5
obj16.Transparency = 0.5
obj16.Visible = true
obj16.ZIndex = 1
obj16.BorderSizePixel = 0
obj16.Parent = obj11

local obj17 = Instance.new("TextButton")
obj17.Name = "HomeBtn"
obj17.Size = UDim2.new(0, 271, 0, 50)
obj17.Position = UDim2.new(0.0255586822, 0, 0.175240785, 0)
obj17.Text = "Home"
obj17.BackgroundColor3 = Color3.fromRGB(255, 140, 0)
obj17.BackgroundTransparency = 0
obj17.Transparency = 0
obj17.Visible = true
obj17.ZIndex = 1
obj17.Font = Enum.Font.FredokaOne
obj17.TextScaled = true
obj17.BorderSizePixel = 0
obj17.Parent = obj16

local obj18 = Instance.new("UICorner")
obj18.Name = "UICorner"
obj18.Parent = obj17

local obj19 = Instance.new("UICorner")
obj19.Name = "UICorner"
obj19.Parent = obj16

local obj20 = Instance.new("TextButton")
obj20.Name = "ExecBtn"
obj20.Size = UDim2.new(0, 271, 0, 50)
obj20.Position = UDim2.new(0.0324552357, 0, 0.582772195, 0)
obj20.Text = "Executor"
obj20.BackgroundColor3 = Color3.fromRGB(255, 140, 0)
obj20.BackgroundTransparency = 0
obj20.Transparency = 0
obj20.Visible = true
obj20.ZIndex = 1
obj20.Font = Enum.Font.FredokaOne
obj20.TextScaled = true
obj20.BorderSizePixel = 0
obj20.Parent = obj16

local obj21 = Instance.new("UICorner")
obj21.Name = "UICorner"
obj21.Parent = obj20

local obj22 = Instance.new("Frame")
obj22.Name = "Menu"
obj22.Size = UDim2.new(0, 856, 0, 367)
obj22.Position = UDim2.new(0.207367197, 0, 0.462673604, 0)
obj22.BackgroundColor3 = Color3.fromRGB(255, 140, 0)
obj22.BackgroundTransparency = 0.5
obj22.Transparency = 0.5
obj22.Visible = true
obj22.ZIndex = 1
obj22.BorderSizePixel = 0
obj22.Parent = obj1

local obj23 = Instance.new("UICorner")
obj23.Name = "UICorner"
obj23.Parent = obj22

local obj24 = Instance.new("Frame")
obj24.Name = "Exec"
obj24.Size = UDim2.new(0, 812, 0, 326)
obj24.Position = UDim2.new(0.0257009342, 0, 0.0544957481, 0)
obj24.BackgroundColor3 = Color3.fromRGB(255, 140, 0)
obj24.BackgroundTransparency = 0.30000001192092896
obj24.Transparency = 0.30000001192092896
obj24.Visible = false
obj24.ZIndex = 1
obj24.BorderSizePixel = 0
obj24.Parent = obj22

local obj25 = Instance.new("UICorner")
obj25.Name = "UICorner"
obj25.Parent = obj24

local obj26 = Instance.new("TextButton")
obj26.Name = "ExecBtn"
obj26.Size = UDim2.new(0, 142, 0, 50)
obj26.Position = UDim2.new(0.00985221658, 0, 0.820194364, 0)
obj26.Text = "EXECUTE"
obj26.BackgroundColor3 = Color3.fromRGB(255, 230, 102)
obj26.BackgroundTransparency = 0
obj26.Transparency = 0
obj26.Font = Enum.Font.IndieFlower
obj26.Visible = true
obj26.ZIndex = 1
obj26.TextScaled = true
obj26.BorderSizePixel = 0
obj26.Parent = obj24

local obj27 = Instance.new("UICorner")
obj27.Name = "UICorner"
obj27.Parent = obj26

local obj28 = Instance.new("TextButton")
obj28.Name = "RTSL"
obj28.Size = UDim2.new(0, 142, 0, 50)
obj28.Position = UDim2.new(0.192118227, 0, 0.820194364, 0)
obj28.Text = "Return to silent"
obj28.BackgroundColor3 = Color3.fromRGB(97, 255, 255)
obj28.BackgroundTransparency = 0
obj28.Transparency = 0
obj28.Font = Enum.Font.IndieFlower
obj28.Visible = true
obj28.ZIndex = 1
obj28.TextScaled = true
obj28.BorderSizePixel = 0
obj28.Parent = obj24

local obj29 = Instance.new("UICorner")
obj29.Name = "UICorner"
obj29.Parent = obj28

local obj30 = Instance.new("TextButton")
obj30.Name = "ScanBDR"
obj30.Size = UDim2.new(0, 231, 0, 50)
obj30.Position = UDim2.new(0.697044313, 0, 0.820194364, 0)
obj30.Text = "Scan Backdoor"
obj30.Font = Enum.Font.IndieFlower
obj30.BackgroundColor3 = Color3.fromRGB(255, 115, 90)
obj30.BackgroundTransparency = 0
obj30.Transparency = 0
obj30.Visible = true
obj30.ZIndex = 1
obj30.TextScaled = true
obj30.BorderSizePixel = 0
obj30.Parent = obj24

local obj31 = Instance.new("UICorner")
obj31.Name = "UICorner"
obj31.Parent = obj30

local obj32 = Instance.new("TextBox")
obj32.Name = "TextBox"
obj32.Size = UDim2.new(0, 783, 0, 246)
obj32.Position = UDim2.new(0.0172413792, 0, 0.0306748468, 0)
obj32.Text = ""
obj32.BackgroundColor3 = Color3.fromRGB(138, 138, 138)
obj32.BackgroundTransparency = 0
obj32.Transparency = 0
obj32.Visible = true
obj32.ZIndex = 1
obj32.Font = Enum.Font.SourceSans
obj32.PlaceholderText = ""
obj32.TextScaled = true
obj32.TextXAlignment = Enum.TextXAlignment.Left
obj32.ClearTextOnFocus = false
obj32.TextYAlignment = Enum.TextYAlignment.Top
obj32.BorderSizePixel = 0
obj32.Parent = obj24

local obj33 = Instance.new("UICorner")
obj33.Name = "UICorner"
obj33.Parent = obj32

local obj34 = Instance.new("Frame")
obj34.Name = "Home"
obj34.Size = UDim2.new(0, 833, 0, 346)
obj34.Position = UDim2.new(0.0128504671, 0, 0.0245231614, 0)
obj34.BackgroundColor3 = Color3.fromRGB(255, 140, 0)
obj34.BackgroundTransparency = 0.30000001192092896
obj34.Transparency = 0.30000001192092896
obj34.Visible = true
obj34.ZIndex = 1
obj34.BorderSizePixel = 0
obj34.Parent = obj22

local obj35 = Instance.new("UICorner")
obj35.Name = "UICorner"
obj35.Parent = obj34

local obj36 = Instance.new("ImageLabel")
obj36.Name = "ImageLabel"
obj36.Size = UDim2.new(0, 50, 0, 50)
obj36.Position = UDim2.new(0.0192076825, 0, 0.0433526002, 0)
obj36.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj36.BackgroundTransparency = 0
obj36.Image = "rbxassetid://88774721887954"
obj36.Transparency = 0
obj36.Visible = true
obj36.ZIndex = 1
obj36.ImageColor3 = Color3.fromRGB(255, 255, 255)
obj36.BorderSizePixel = 0
obj36.Parent = obj34

local obj37 = Instance.new("UICorner")
obj37.Name = "UICorner"
obj37.Parent = obj36

local obj38 = Instance.new("TextLabel")
obj38.Name = "TextLabel"
obj38.Size = UDim2.new(0, 200, 0, 50)
obj38.Position = UDim2.new(0.0936374515, 0, 0.0433526002, 0)
obj38.Text = "SM Executor"
obj38.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj38.BackgroundTransparency = 1
obj38.Visible = true
obj38.Font = Enum.Font.Fondamento
obj38.ZIndex = 1
obj38.TextScaled = true
obj38.BorderSizePixel = 0
obj38.Parent = obj34

local obj39 = Instance.new("TextLabel")
obj39.Name = "TextLabel"
obj39.Size = UDim2.new(0, 799, 0, 50)
obj39.Position = UDim2.new(0.0192076825, 0, 0.187861279, 0)
obj39.Text = "Source : https://github.com/scriptmirroroffical"
obj39.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj39.BackgroundTransparency = 1
obj39.Visible = true
obj39.ZIndex = 1
obj39.Font = Enum.Font.Fondamento
obj39.TextScaled = true
obj39.BorderSizePixel = 0
obj39.Parent = obj34

local obj40 = Instance.new("TextLabel")
obj40.Name = "TextLabel"
obj40.Size = UDim2.new(0, 799, 0, 156)
obj40.Position = UDim2.new(0.0204081628, 0, 0.332369953, 0)
obj40.Text = "Description : This Project had been started in the end month of 2025 and all of this project is open-source ,so you can adjust it . Thank you!"
obj40.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj40.BackgroundTransparency = 1
obj40.Visible = true
obj40.ZIndex = 1
obj40.Font = Enum.Font.Fondamento
obj40.TextScaled = true
obj40.BorderSizePixel = 0
obj40.Parent = obj34

local obj41 = Instance.new("TextLabel")
obj41.Name = "TextLabel"
obj41.Size = UDim2.new(0, 800, 0, 50)
obj41.Position = UDim2.new(0.0180072021, 0, 0.812138736, 0)
obj41.Text = "<+><+><+><+><+><+<+><+><+><+><+><+><+><+><+><+><+>"
obj41.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj41.BackgroundTransparency = 1
obj41.Visible = true
obj41.ZIndex = 1
obj41.Font = Enum.Font.Fondamento
obj41.TextScaled = true
obj41.BorderSizePixel = 0
obj41.Parent = obj34

--[[ 
    SM ENGINE PRO CORE v6.0
    TÍCH HỢP TRỰC TIẾP VÀO GUI OMNI-GOD
    FIXED: performUltraScan nil, InputBegan ScreenGui errors
]]

-- ==========================================
-- 1. HỆ THỐNG QUẢN LÝ TRẠNG THÁI (CORE STATE)
-- ==========================================
local EngineState = {
    IsAttached = false,
    SSMode = false,
    TargetRemote = nil,
    Version = "6.0 PRO",
    Scanning = false
}

local Colors = {
    Success = Color3.fromRGB(0, 255, 127),
    Error = Color3.fromRGB(255, 65, 65),
    Warning = Color3.fromRGB(255, 170, 0),
    Info = Color3.fromRGB(0, 170, 255),
    SS = Color3.fromRGB(170, 85, 255)
}

-- ==========================================
-- 2. ĐỊNH NGHĨA HÀM TIỆN ÍCH (CORE UTILS)
-- ==========================================
local function notify(title, msg, color)
    -- Bạn có thể tùy biến thêm popup tại đây
    print("[" .. title .. "]: " .. msg)
end

-- Hàm kéo thả an toàn (Fix lỗi InputBegan trên ScreenGui)
local function makeDraggable(frame)
    if not frame or not frame:IsA("GuiObject") then return end
    
    local dragging, dragInput, dragStart, startPos
    frame.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
            dragging = true
            dragStart = input.Position
            startPos = frame.Position
            input.Changed:Connect(function()
                if input.UserInputState == Enum.UserInputState.End then dragging = false end
            end)
        end
    end)
    
    game:GetService("UserInputService").InputChanged:Connect(function(input)
        if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then
            local delta = input.Position - dragStart
            frame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
        end
    end)
end

-- ==========================================
-- 3. THUẬT TOÁN GHOST HUNTER (SCAN BACKDOOR)
-- ==========================================
local function isGhostBackdoor(obj)
    if not (obj:IsA("RemoteEvent") or obj:IsA("RemoteFunction")) then return false end
    local path = obj:GetFullName():lower()
    if path:find("chat") or path:find("voice") or path:find("appearance") then return false end

    local parent = obj.Parent
    if not parent then return false end

    local suspectServices = {"JointsService", "TestService", "LogService", "Lighting"}
    for _, srv in ipairs(suspectServices) do
        if parent:IsA(srv) or obj:IsDescendantOf(game:GetService(srv)) then return true end
    end
    return false
end

-- ==========================================
-- SIÊU LÕI QUÉT BACKDOOR (SM-DEEP-SCAN)
-- ==========================================

local function ultraDeepScan()
    if EngineState.Scanning then return end
    EngineState.Scanning = true
    
    -- Phản hồi giao diện
    obj30.Text = "ĐANG QUÉT SÂU..."
    obj30.BackgroundColor3 = Color3.fromRGB(255, 170, 0)
    EngineState.TargetRemote = nil
    
    local foundRemotes = {}
    
    -- Danh sách các nơi backdoor hay ẩn nấp mà script thường bỏ qua
    local scanLocations = {
        game:GetService("ReplicatedStorage"),
        game:GetService("JointsService"),
        game:GetService("Lighting"),
        game:GetService("LogService"),
        workspace
    }

    task.spawn(function()
        for _, location in ipairs(scanLocations) do
            for _, v in ipairs(location:GetDescendants()) do
                if v:IsA("RemoteEvent") or v:IsA("RemoteFunction") then
                    local name = v.Name:lower()
                    -- Thuật toán nhận diện backdoor của LALOL (Quét theo từ khóa và độ dài tên)
                    if name:find("run") or name:find("exec") or name:find("load") or 
                       name:find("serve") or name:find("remote") or #v.Name > 25 then
                        
                        -- Kiểm tra xem có phải bẫy (Trap) của Admin không
                        if not name:find("check") and not name:find("admin") then
                            table.insert(foundRemotes, v)
                        end
                    end
                end
            end
            task.wait() -- Tránh treo máy
        end

        if #foundRemotes > 0 then
            EngineState.TargetRemote = foundRemotes[1]
            EngineState.SSMode = true
            obj26.Text = "THỰC THI (SS)" -- Chuyển sang chế độ Server Side
            obj26.BackgroundColor3 = Color3.fromRGB(170, 85, 255)
            obj30.Text = "TÌM THẤY: " .. #foundRemotes
            obj30.BackgroundColor3 = Color3.fromRGB(0, 255, 127)
        else
            obj30.Text = "KHÔNG CÓ BACKDOOR"
            obj30.BackgroundColor3 = Color3.fromRGB(255, 65, 65)
            task.wait(2)
            obj30.Text = "Scan Backdoor"
            obj30.BackgroundColor3 = Color3.fromRGB(255, 115, 90)
        end
        EngineState.Scanning = false
    end)
end

-- KẾT NỐI LẠI NÚT BẤM (Đảm bảo không bị lỗi NIL)
obj30.MouseButton1Click:Connect(ultraDeepScan)
-- ==========================================
-- 4. KÍCH HOẠT LOGIC VÀO GUI CỦA BẠN
-- ==========================================

-- Kéo thả cho MainMenu (obj11) và Menu (obj22)
makeDraggable(obj11)
makeDraggable(obj22)

-- Nút Chuyển Tab (Home / Executor)
obj17.MouseButton1Click:Connect(function()
    obj34.Visible = true
    obj24.Visible = false
end)

obj20.MouseButton1Click:Connect(function()
    obj34.Visible = false
    obj24.Visible = true
end)

-- Nút Toggle GUI (obj7)
local isVisible = true
obj7.MouseButton1Click:Connect(function()
    isVisible = not isVisible
    obj11.Visible = isVisible
    obj22.Visible = isVisible
    -- Hiệu ứng nhấn
    game:GetService("TweenService"):Create(obj3, TweenInfo.new(0.2), {BackgroundTransparency = isVisible and 0.4 or 0.8}):Play()
end)


-- Nút Reset Silent (obj28)
obj28.MouseButton1Click:Connect(function()
    EngineState.SSMode = false
    EngineState.TargetRemote = nil
    obj26.Text = "EXECUTE"
    obj26.BackgroundColor3 = Color3.fromRGB(255, 230, 102)
    obj32.Text = ""
    notify("System", "Backdoor cache cleared.", Colors.Info)
end)

-- Nút Execute (obj26) - PRO Logic
obj26.MouseButton1Click:Connect(function()
    local code = obj32.Text
    if code == "" then return end

    if EngineState.SSMode and EngineState.TargetRemote then
        -- Kỹ thuật tàng hình gửi code qua Remote
        local wrappedCode = "spawn(function() " .. code .. " end)"
        pcall(function()
            if EngineState.TargetRemote:IsA("RemoteEvent") then
                EngineState.TargetRemote:FireServer(wrappedCode)
            else
                EngineState.TargetRemote:InvokeServer(wrappedCode)
            end
        end)
    else
        -- Chạy Client-Side bình thường
        local load = loadstring or getgenv().loadstring
        if load then
            local f, err = load(code)
            if f then 
                local success, runtimeErr = pcall(f) 
                if not success then notify("Error", runtimeErr, Colors.Error) end
            else 
                notify("Syntax", err, Colors.Error) 
            end
        else
            notify("System", "Executor không hỗ trợ loadstring.", Colors.Error)
        end
    end
end)

-- ==========================================
-- 5. HIỆU ỨNG VÀ KHỞI CHẠY (FINAL)
-- ==========================================

-- Logo Rotation (obj3)
local runService = game:GetService("RunService")
local angle = 0
runService.RenderStepped:Connect(function(dt)
    angle = angle + 45 * dt
    if obj3 then obj3.Rotation = angle end
end)

-- Thông báo chào mừng
notify("SM Engine", "Omni-God PRO Core v6.0 Loaded!", Colors.Success)
